// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbgxmbxaermmkpxmkkju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZ3htYnhhZXJtbWtweG1ra2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NjI2ODYsImV4cCI6MjA2MDQzODY4Nn0.c6H7cNBW8EQpMqzera3oJN5kEW3_1TKutPLj3SUv-Dc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);